import React, { useState } from 'react';
import { 
  ResponsiveContainer, 
  AreaChart, Area 
} from 'recharts';
import GlowButton from '../components/GlowButton';
import RiskBubbleChart from '../components/RiskBubbleChart';
import IntegrityGauge from '../components/IntegrityGauge';
import TopThreatsTable from '../components/TopThreatsTable';

const Dashboard = () => {
  const [reportDownloaded, setReportDownloaded] = useState(false);

  const kpiData = [
    { title: 'Total Threats Detected', value: 245, delta: '+5.3% ▲', deltaColor: 'text-[#00ff88]', color: 'text-danger', border: 'border-danger/30', fill: '#ff4444' },
    { title: 'Defended (Patched)', value: 158, delta: '+12.1% ▲', deltaColor: 'text-[#00ff88]', color: 'text-primary', border: 'border-primary/30', fill: '#00ff88' },
    { title: 'Failed / Vulnerable', value: 37, delta: '-2.1% ▼', deltaColor: 'text-[#ff4444]', color: 'text-danger', border: 'border-danger/30', fill: '#ff4444' },
    { title: 'Total Files Scanned', value: 3845, delta: '+8.4% ▲', deltaColor: 'text-[#00ff88]', color: 'text-secondary', border: 'border-secondary/30', fill: '#00d4ff' },
  ];

  const downloadDashboardReport = () => {
    const now = new Date();
    const dateStr = now.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    const timeStr = now.toLocaleTimeString("en-US");
    const reportId = `QB-RPT-${Date.now().toString(36).toUpperCase()}`;

    const report = `
╔══════════════════════════════════════════════════════════════════════════╗
║                  QUANTUMBRIDGE — SECURITY DASHBOARD REPORT              ║
╚══════════════════════════════════════════════════════════════════════════╝

Report ID   : ${reportId}
Generated   : ${dateStr} at ${timeStr}
Platform    : QuantumBridge v1.0 | Team Phoenix | Cyberonites | GLA University

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EXECUTIVE SUMMARY
─────────────────
Total Threats Detected    :  245   (+5.3% vs last week)
Defended / Patched        :  158   (+12.1% vs last week)
Failed / Vulnerable       :  37    (-2.1% vs last week)
Total Files Scanned       :  3845  (+8.4% vs last week)

SECURITY INTEGRITY SCORE  :  7869 / 10000
  Critical Components     :  2573
  Suspicious Components   :  2117
  Safe Components         :  3179

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

RISK DISTRIBUTION
─────────────────
  At Risk          :  3,652 components  (HIGH PRIORITY)
  New Detections   :  1,786 components
  Breached         :    989 components  (CRITICAL)
  Dormant          :  1,945 components
  Monitored        :    828 components
  Idle             :  1,289 components

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TOP CRITICAL THREATS
────────────────────
1. Sequential Breach
   Algorithm : RSA-2048          Severity : CRITICAL (92/100)
   File      : auth/rsa_handler.py
   Status    : ACTIVE
   Action    : Patch RSA → ML-KEM-768 (NIST FIPS 203)

2. Global Disruption
   Algorithm : ECDSA P-256       Severity : HIGH (74/100)
   File      : crypto/ecdsa_sign.js
   Status    : MONITORING
   Action    : Replace ECDSA → ML-DSA-65 (NIST FIPS 204)

3. Analytical Deduction
   Algorithm : DHE-RSA           Severity : HIGH (68/100)
   File      : config/ssl.conf
   Status    : FLAGGED
   Action    : Migrate DHE → ML-KEM-1024 (NIST FIPS 203)

4. Key Exposure Vector
   Algorithm : RSA-1024          Severity : CRITICAL (88/100)
   File      : services/tls_config.py
   Status    : ACTIVE
   Action    : Immediate — RSA-1024 is critically weak

5. Legacy Hash Collision
   Algorithm : MD5               Severity : MEDIUM (45/100)
   File      : utils/checksum.go
   Status    : RESOLVED
   Action    : Upgrade MD5 → SHA3-256 (NIST FIPS 202)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

RECOMMENDED IMMEDIATE ACTIONS
──────────────────────────────
1. [URGENT] Patch RSA-2048 instances in auth/rsa_handler.py → ML-KEM-768
2. [URGENT] Patch RSA-1024 in services/tls_config.py — critically weak key size
3. [HIGH]   Replace ECDSA usage in crypto/ecdsa_sign.js → ML-DSA-65
4. [HIGH]   Update DHE-RSA config in config/ssl.conf → ML-KEM-1024
5. [MEDIUM] Upgrade MD5 in utils/checksum.go → SHA3-256

NIST COMPLIANCE STATUS
──────────────────────
  NIST FIPS 203 (ML-KEM) — Key Encapsulation   :  PARTIAL
  NIST FIPS 204 (ML-DSA) — Digital Signatures  :  PARTIAL
  NIST FIPS 205 (SLH-DSA) — Hash Signatures    :  NON-COMPLIANT
  CNSA 2.0 Suite                                :  NON-COMPLIANT
  BSI Recommendations                           :  PARTIAL

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by QuantumBridge Security Platform
Team Phoenix | Cyberonites | GLA University | IntrusionX Second Edition
Verify at: quantumbridge.io/verify/${reportId}
  `.trim();

    const blob = new Blob([report], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `QuantumBridge_Dashboard_Report_${now.toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    // Show success feedback on the button
    setReportDownloaded(true);
    setTimeout(() => setReportDownloaded(false), 3000);
  };

  const threatSparkData = [180, 210, 195, 230, 225, 240, 245].map(v => ({ v }));

  return (
    <div className="min-h-screen pt-24 pb-12 px-4 sm:px-8 max-w-7xl mx-auto animate-[fadeIn_0.3s_ease-out]">
      <div className="flex justify-between items-center mb-8">
        <h1 className="text-3xl font-bold font-sans">Security <span className="text-secondary">Dashboard</span></h1>
        <button
          onClick={downloadDashboardReport}
          style={{
            background: reportDownloaded ? "#00ff88" : "transparent",
            border: `1px solid ${reportDownloaded ? "#00ff88" : "#00d4ff"}`,
            color: reportDownloaded ? "#000" : "#00d4ff",
            borderRadius: "8px",
            padding: "10px 20px",
            fontSize: "13px",
            fontWeight: "700",
            cursor: "pointer",
            transition: "all 0.3s ease",
            letterSpacing: "0.5px",
            boxShadow: reportDownloaded ? "0 0 20px rgba(0,255,136,0.4)" : "0 0 10px rgba(0,212,255,0.15)",
            display: "flex",
            alignItems: "center",
            gap: "8px",
          }}
          onMouseEnter={e => {
            if (!reportDownloaded) {
              e.currentTarget.style.background = "rgba(0,212,255,0.08)";
              e.currentTarget.style.boxShadow = "0 0 20px rgba(0,212,255,0.3)";
            }
          }}
          onMouseLeave={e => {
            if (!reportDownloaded) {
              e.currentTarget.style.background = "transparent";
              e.currentTarget.style.boxShadow = "0 0 10px rgba(0,212,255,0.15)";
            }
          }}
        >
          {reportDownloaded ? "✓ Downloaded!" : "⬇ Download Report"}
        </button>
      </div>

      {/* KPI Row (4x CSS grid) */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        {kpiData.map((kpi, i) => (
          <div key={i} className={`glass-card p-4 border-t-4 ${kpi.border} flex flex-col justify-between`}>
            <div>
              <div className="flex justify-between items-start mb-2">
                <h3 className="text-gray-400 text-xs font-semibold uppercase tracking-wider">{kpi.title}</h3>
                <span className={`text-xs font-bold ${kpi.deltaColor}`}>{kpi.delta}</span>
              </div>
              <div className={`text-4xl font-mono font-bold ${kpi.color}`}>{kpi.value}</div>
            </div>
            <div className="h-12 w-full mt-4">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={threatSparkData}>
                  <Area type="monotone" dataKey="v" stroke="none" fill={kpi.fill} fillOpacity={0.2} />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </div>
        ))}
      </div>

      {/* Middle Row Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
        
        {/* Security Integrity Gauge */}
        <div className="glass-card p-6 min-h-[380px] flex flex-col">
          <h2 className="text-xl font-bold mb-6">Security Integrity Gauge</h2>
          <IntegrityGauge />
        </div>

        {/* Risk Distribution Bubble Chart */}
        <div className="glass-card p-6 min-h-[380px] flex flex-col">
          <h2 className="text-xl font-bold mb-6">Risk Distribution</h2>
          <RiskBubbleChart />
        </div>

      </div>

      {/* Bottom Table */}
      <div className="glass-card p-6 overflow-hidden flex flex-col">
        <TopThreatsTable />
      </div>
    </div>
  );
};

export default Dashboard;
